trigger:
  - master

pool:
  name: Default
  demands:
    - agent.name -equals smartlite

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm run build
    displayName: 'Build Project'

  - script: |
      npm run start
    displayName: 'Run Production Server (Optional)'
    condition: false  # Set to `true` if you want to run prod server here

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'web/.next'
      ArtifactName: 'flatris-next-build'
      publishLocation: 'Container'
    displayName: 'Publish .next Build Artifact'
