trigger:
  - master

pool:
  name: Default
  demands:
    - agent.name -equals smartlite

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    workingDirectory: 'web'
    displayName: 'Install Dependencies'

  - script: |
      npm run build
    workingDirectory: 'web'
    displayName: 'Build Project'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/web'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/flatris.zip'
      replaceExistingArchive: true
    displayName: 'Archive Web Folder for Deployment'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/flatris.zip'
      ArtifactName: 'flatris-next-build'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifact'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'az-flatristst-conn'   
      appType: 'webApp'
      appName: 'flatristst'                    
      package: '$(Build.ArtifactStagingDirectory)/flatris.zip'
    displayName: 'Deploy to Azure Web App'
